### ISSUE TITLE
JsonException if using Search.AdvancedAsync

### ISSUE THREAD

**Issue by dacorp** [tofudd/RadioBrowser#2]
**Example**:
radioBrowser.Search.AdvancedAsync(new AdvancedSearchOptions() { Countrycode = "DE" }),

**Error**:
JsonException: The JSON value could not be converted to System.Uri. Path: $[1799].homepage

Exact error for Favicon, too.

So, deserialization on Homepage and Favicon property does not work properly.

**Comment by tofudd** [comment]
Thanks for feedback I'll check it.

**Comment by tofudd** [comment]
Fixed in https://github.com/tofudd/RadioBrowser/commit/57abea98ed04ea32b596b7772da3bea30dee3448
