### ISSUE TITLE
Can't run in Blazor WebAssembly

### ISSUE THREAD

**Issue by dacorp** [tofudd/RadioBrowser#3]
Running in Blazor WebAssembly application, on fetching data, throws error:
Unhandled exception rendering component: System.Net.NameResolution is not supported on this platform.

I think it is due this line:
https://github.com/tofudd/RadioBrowser/blob/83c0d443b1b1b234e31b0241bbe554fe2835e51c/RadioBrowser/Internals/HttpClient.cs#L36

**Comment by tofudd** [comment]
You can skip dns resolving by passing api url in constructor parameter.

```csharp
var radioBrowser = new RadioBrowserClient("https://de1.api.radio-browser.info");
```

**Comment by dacorp** [comment]
Oh, thanks! Small correction, must be: new RadioBrowserClient("de1.api.radio-browser.info"); (without 'https://')
