### ISSUE TITLE
Package RadioBrowser 0.6.0 is not compatible with netstandard2.0

### ISSUE THREAD

**Issue by dacorp** [tofudd/RadioBrowser#4]
When adding nuget package to Xamarin.Forms project, error occurs:

Package RadioBrowser 0.6.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package RadioBrowser 0.6.0 supports: net5.0 (.NETCoreApp,Version=v5.0).

Compatibility with netstandard2.0 and using this useful nuget in Xamarin projects would be great.

**Comment by tofudd** [comment]
I added netstandard2.1 target in https://github.com/tofudd/RadioBrowser/commit/90327bdbb49fc4388350738a96c4a2c6188277e6. Now it should works with Xamarin 10.0+.
